import { useMemo, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { bookingAPI } from '../../services/api';
import { PublicPageShell } from '../../components/common/PublicPageShell';
import {
  FiArrowRight,
  FiCalendar,
  FiCheck,
  FiClock,
  FiCreditCard,
  FiDownload,
  FiGift,
  FiGlobe,
  FiHeart,
  FiMapPin,
  FiShare2,
  FiShield,
  FiStar,
  FiUsers,
  FiSun,
} from 'react-icons/fi';

const paymentMethods = [
  { key: 'upi', label: 'UPI', note: 'Fastest secure checkout', icon: FiClock },
  { key: 'card', label: 'Card', note: 'Credit / debit supported', icon: FiCreditCard },
  { key: 'wallet', label: 'Wallet', note: 'Pay from saved balance', icon: FiHeart },
  { key: 'emi', label: 'EMI', note: 'Split into easy parts', icon: FiGift },
];

const supportCards = [
  { title: 'Secure confirmation', value: 'Encrypted Razorpay flow with booking verification.' },
  { title: 'Smart reminders', value: 'Add to calendar and keep the ticket accessible offline.' },
  { title: 'Live tracking', value: 'Your route stays visible after confirmation.' },
  { title: 'Priority help', value: 'Instant support for boarding, timings, and change requests.' },
];

const formatDate = (date) => new Date(date).toLocaleDateString(undefined, {
  weekday: 'short',
  month: 'short',
  day: 'numeric',
  year: 'numeric',
});

export default function Payment() {
  const { bookingId } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const { orderId, amount, trip, bus, selectedDate, selectedSeats } = location.state || {};

  const [processing, setProcessing] = useState(false);
  const [paymentMethod, setPaymentMethod] = useState('upi');
  const [couponCode, setCouponCode] = useState('');
  const [couponApplied, setCouponApplied] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [paymentSnapshot, setPaymentSnapshot] = useState(null);

  const totalAmount = Number(amount || 0);
  const discount = couponApplied ? 300 : 0;
  const payableAmount = Math.max(totalAmount - discount, 0);

  const loadRazorpayScript = () => new Promise((resolve) => {
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });

  const handleShare = async () => {
    const shareData = {
      title: 'Weekend Mojo booking',
      text: `Booking ${bookingId} is confirmed for ${trip?.title || 'your trip'}.`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
        return;
      } catch (error) {
        toast.error('Sharing was cancelled');
      }
    }

    toast.success('Share link copied to clipboard');
  };

  const handleDownload = () => {
    toast.success('Ticket PDF will be generated by the backend download flow');
  };

  const handleAddCalendar = () => {
    toast.success('Calendar reminder prepared');
  };

  const handlePayment = async () => {
    if (!orderId) {
      toast.error('Missing Razorpay order information');
      return;
    }

    setProcessing(true);

    const scriptLoaded = await loadRazorpayScript();
    if (!scriptLoaded) {
      toast.error('Failed to load payment gateway');
      setProcessing(false);
      return;
    }

    const options = {
      key: import.meta.env.VITE_RAZORPAY_KEY_ID,
      amount: payableAmount * 100,
      currency: 'INR',
      name: 'Weekend Mojo',
      description: 'Premium travel booking checkout',
      order_id: orderId,
      handler: async (response) => {
        try {
          const verifyResponse = await bookingAPI.confirmPayment({
            razorpay_order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
            bookingId,
          });

          if (verifyResponse.data.success) {
            toast.success('Payment successful! Booking confirmed.');
            setConfirmed(true);
            setPaymentSnapshot({
              paymentId: response.razorpay_payment_id,
              orderId: response.razorpay_order_id,
            });
          } else {
            toast.error('Payment verification failed');
          }
        } catch (error) {
          toast.error(error.response?.data?.error || 'Payment verification failed');
        } finally {
          setProcessing(false);
        }
      },
      prefill: {
        name: localStorage.getItem('userName') || '',
        email: localStorage.getItem('userEmail') || '',
      },
      theme: {
        color: '#2563eb',
      },
      modal: {
        ondismiss: () => {
          setProcessing(false);
          toast.error('Payment cancelled');
        },
      },
    };

    const razorpay = new window.Razorpay(options);
    razorpay.open();
  };

  const bookingSummary = useMemo(() => [
    { label: 'Booking ID', value: bookingId || 'Pending' },
    { label: 'Trip', value: trip?.title || 'Selected trip' },
    { label: 'Date', value: selectedDate ? formatDate(selectedDate) : 'Select a date' },
    { label: 'Seats', value: selectedSeats?.length ? selectedSeats.join(', ') : 'Not assigned' },
    { label: 'Bus', value: bus?.busNumber || 'Assigned vehicle' },
  ], [bookingId, trip, selectedDate, selectedSeats, bus]);

  if (confirmed) {
    return (
      <PublicPageShell
        eyebrow="Booking Confirmed"
        title="Your ticket is ready"
        subtitle="The premium confirmation screen keeps the ticket, share actions, and live tracking in one place."
        className="pb-12"
      >
        <div className="mx-auto max-w-5xl px-4 pb-10 sm:px-6 lg:px-8">
          <div className="booking-success-card overflow-hidden">
            <div className="absolute inset-x-0 top-0 h-40 bg-gradient-to-r from-sky-500 via-blue-600 to-orange-400 opacity-90" />
            <div className="relative grid gap-6 p-5 sm:p-6 lg:grid-cols-[1.15fr_0.85fr]">
              <div className="rounded-[1.6rem] border border-white/20 bg-white/10 p-5 text-white backdrop-blur-xl">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold uppercase tracking-[0.24em]">
                      <FiCheck /> Confirmed
                    </div>
                    <h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Boarding pass style ticket reveal</h2>
                    <p className="mt-2 max-w-xl text-sm text-slate-100/90">Your booking is locked, the ticket is saved, and the follow-up actions are ready in one elegant confirmation view.</p>
                  </div>
                  <div className="rounded-[1.5rem] bg-white/15 p-4 text-white backdrop-blur">
                    <FiStar className="text-2xl" />
                  </div>
                </div>

                <div className="mt-6 grid gap-3 sm:grid-cols-2">
                  {bookingSummary.map((item) => (
                    <div key={item.label} className="rounded-[1.35rem] border border-white/10 bg-white/10 p-4 backdrop-blur">
                      <div className="text-[10px] uppercase tracking-[0.22em] text-slate-200/70">{item.label}</div>
                      <div className="mt-1 text-sm font-semibold text-white">{item.value}</div>
                    </div>
                  ))}
                </div>

                <div className="mt-6 rounded-[1.5rem] border border-white/15 bg-white/10 p-4 backdrop-blur-xl">
                  <div className="flex items-center justify-between gap-4 text-sm text-slate-100/90">
                    <span>Payment ID</span>
                    <span className="font-medium">{paymentSnapshot?.paymentId || 'Captured successfully'}</span>
                  </div>
                  <div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-100/85">
                    <span className="rounded-full bg-white/10 px-3 py-1">UPI / Card / Wallet</span>
                    <span className="rounded-full bg-white/10 px-3 py-1">Offline access</span>
                    <span className="rounded-full bg-white/10 px-3 py-1">Live tracking ready</span>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <div className="booking-ticket bg-white p-5 shadow-[0_24px_80px_-40px_rgba(15,23,42,0.4)]">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <div className="text-xs uppercase tracking-[0.24em] text-slate-400">Ticket card</div>
                      <div className="mt-1 text-2xl font-semibold text-slate-950">{trip?.title || 'Weekend Mojo Trip'}</div>
                    </div>
                    <div className="rounded-2xl bg-slate-950 p-3 text-white">
                      <FiShield />
                    </div>
                  </div>

                  <div className="mt-5 grid gap-3 sm:grid-cols-2">
                    <div className="rounded-[1.2rem] bg-slate-50 p-4">
                      <div className="text-[10px] uppercase tracking-[0.22em] text-slate-400">Booking amount</div>
                      <div className="mt-1 text-2xl font-semibold text-slate-950">₹{payableAmount.toLocaleString()}</div>
                    </div>
                    <div className="rounded-[1.2rem] bg-slate-50 p-4">
                      <div className="text-[10px] uppercase tracking-[0.22em] text-slate-400">Seats</div>
                      <div className="mt-1 text-2xl font-semibold text-slate-950">{selectedSeats?.length || 0}</div>
                    </div>
                    <div className="rounded-[1.2rem] bg-slate-50 p-4">
                      <div className="text-[10px] uppercase tracking-[0.22em] text-slate-400">Travel date</div>
                      <div className="mt-1 text-sm font-semibold text-slate-950">{selectedDate ? formatDate(selectedDate) : 'Scheduled soon'}</div>
                    </div>
                    <div className="rounded-[1.2rem] bg-slate-50 p-4">
                      <div className="text-[10px] uppercase tracking-[0.22em] text-slate-400">Boarding</div>
                      <div className="mt-1 text-sm font-semibold text-slate-950">{bus?.busNumber || 'Assigned vehicle'}</div>
                    </div>
                  </div>

                  <div className="mt-5 rounded-[1.35rem] border border-slate-200 bg-slate-950 p-4 text-white">
                    <div className="text-xs uppercase tracking-[0.24em] text-slate-300/70">QR placeholder</div>
                    <div className="mt-3 grid grid-cols-6 gap-1">
                      {Array.from({ length: 36 }, (_, index) => (
                        <span key={index} className={`h-3 rounded-[0.2rem] ${index % 3 === 0 || index % 7 === 0 ? 'bg-white' : 'bg-white/20'}`} />
                      ))}
                    </div>
                    <div className="mt-3 text-sm text-slate-200/80">Use this ticket at boarding and keep it offline in your wallet.</div>
                  </div>
                </div>

                <div className="rounded-[1.5rem] border border-white/70 bg-white/90 p-4 shadow-[0_20px_70px_-40px_rgba(15,23,42,0.35)] backdrop-blur">
                  <div className="grid gap-3 sm:grid-cols-3">
                    <button type="button" onClick={handleDownload} className="btn-secondary">
                      <FiDownload className="mr-2" /> Download PDF
                    </button>
                    <button type="button" onClick={handleShare} className="btn-secondary">
                      <FiShare2 className="mr-2" /> Share ticket
                    </button>
                    <button type="button" onClick={handleAddCalendar} className="btn-secondary">
                      <FiCalendar className="mr-2" /> Add to calendar
                    </button>
                  </div>
                  <Link to="/dashboard" className="btn-primary mt-4 flex w-full items-center justify-center">
                    Open dashboard <FiArrowRight className="ml-2" />
                  </Link>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_1fr]">
            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Live tracking preview</h3>
                <p className="booking-panel-subtitle">A calm at-a-glance route view for the next travel phase.</p>
              </div>
              <div className="booking-panel-body">
                <div className="rounded-[1.5rem] bg-gradient-to-br from-slate-950 via-slate-900 to-blue-800 p-4 text-white shadow-lg">
                  <div className="flex items-center justify-between gap-3 text-sm">
                    <span>{trip?.location || 'Destination'}</span>
                    <span className="rounded-full bg-white/10 px-3 py-1">On schedule</span>
                  </div>
                  <div className="mt-4 h-36 rounded-[1.5rem] border border-white/10 bg-white/10 p-4 backdrop-blur">
                    <div className="flex h-full items-end justify-between gap-2">
                      <div className="h-12 w-1/4 rounded-t-[1rem] bg-white/20" />
                      <div className="h-20 w-1/4 rounded-t-[1rem] bg-white/30" />
                      <div className="h-28 w-1/4 rounded-t-[1rem] bg-white/40" />
                      <div className="h-16 w-1/4 rounded-t-[1rem] bg-orange-300/70" />
                    </div>
                  </div>
                  <div className="mt-3 flex items-center gap-2 text-xs text-slate-100/85">
                    <FiMapPin /> Boarding point, route preview, and stop info will appear here.
                  </div>
                </div>
              </div>
            </div>

            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Next steps</h3>
                <p className="booking-panel-subtitle">Everything remains discoverable from the confirmation screen.</p>
              </div>
              <div className="booking-panel-body space-y-3">
                {supportCards.map((card) => (
                  <div key={card.title} className="rounded-[1.35rem] border border-slate-200 bg-slate-50 p-4">
                    <div className="text-sm font-semibold text-slate-950">{card.title}</div>
                    <div className="mt-1 text-sm text-slate-600">{card.value}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </PublicPageShell>
    );
  }

  return (
    <PublicPageShell
      eyebrow="Secure Checkout"
      title="Complete your payment"
      subtitle="A premium Razorpay checkout wrapped in a futuristic, mobile-first payment experience."
      className="pb-12"
    >
      <div className="mx-auto max-w-6xl px-4 pb-10 sm:px-6 lg:px-8">
        <div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]">
          <div className="space-y-5">
            <div className="booking-hero-card">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <div className="text-[11px] font-bold uppercase tracking-[0.3em] text-sky-100/80">Checkout</div>
                  <h2 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Pay securely and unlock confirmation instantly.</h2>
                  <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-200/85">Choose a payment mode, apply a coupon, and finish with a ticket reveal that keeps support actions within reach.</p>
                </div>
                <div className="rounded-2xl bg-white/10 p-3 text-white backdrop-blur">
                  <FiShield className="text-2xl" />
                </div>
              </div>

              <div className="mt-5 flex flex-wrap gap-2">
                <span className="travel-chip travel-chip-ghost bg-white/10 text-white/90">UPI</span>
                <span className="travel-chip travel-chip-ghost bg-white/10 text-white/90">Card</span>
                <span className="travel-chip travel-chip-ghost bg-white/10 text-white/90">Wallet</span>
                <span className="travel-chip travel-chip-ghost bg-white/10 text-white/90">EMI</span>
              </div>
            </div>

            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Payment methods</h3>
                <p className="booking-panel-subtitle">The selected mode updates the checkout tone and visuals.</p>
              </div>
              <div className="booking-panel-body grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                {paymentMethods.map((method) => {
                  const MethodIcon = method.icon;
                  const isActive = paymentMethod === method.key;
                  return (
                    <button key={method.key} type="button" onClick={() => setPaymentMethod(method.key)} className={`booking-option-card text-left ${isActive ? 'booking-option-card-active' : ''}`}>
                      <span className={`booking-option-icon ${isActive ? 'booking-option-icon-active' : ''}`}>
                        <MethodIcon />
                      </span>
                      <span className="mt-3 block text-base font-semibold text-slate-950">{method.label}</span>
                      <span className="mt-1 block text-xs text-slate-500">{method.note}</span>
                    </button>
                  );
                })}
              </div>
            </div>

            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Coupon and security</h3>
                <p className="booking-panel-subtitle">A minimal form with a premium summary card.</p>
              </div>
              <div className="booking-panel-body grid gap-4 sm:grid-cols-2">
                <label className="travel-field">
                  <span className="travel-field-label">Coupon code</span>
                  <div className="travel-field-control">
                    <input
                      type="text"
                      value={couponCode}
                      onChange={(event) => setCouponCode(event.target.value)}
                      placeholder="Enter coupon code"
                      className="travel-field-input"
                    />
                    <button type="button" onClick={() => setCouponApplied(Boolean(couponCode.trim()))} className="travel-chip travel-chip-active">
                      Apply
                    </button>
                  </div>
                </label>

                <div className="rounded-[1.35rem] border border-slate-200 bg-slate-50 p-4">
                  <div className="flex items-center justify-between gap-3">
                    <div>
                      <div className="text-xs uppercase tracking-[0.24em] text-slate-400">Encrypted checkout</div>
                      <div className="mt-1 text-base font-semibold text-slate-950">Razorpay secure transaction</div>
                    </div>
                    <FiShield className="text-sky-600" />
                  </div>
                  <div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-600">
                    <span className="rounded-full bg-white px-3 py-1 shadow-sm">PCI-safe</span>
                    <span className="rounded-full bg-white px-3 py-1 shadow-sm">Fast confirm</span>
                    <span className="rounded-full bg-white px-3 py-1 shadow-sm">Instant ticket</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Payment ready summary</h3>
                <p className="booking-panel-subtitle">Review the booking snapshot before hitting pay now.</p>
              </div>
              <div className="booking-panel-body grid gap-4 sm:grid-cols-2">
                {bookingSummary.map((item) => (
                  <div key={item.label} className="rounded-[1.35rem] border border-slate-200 bg-slate-50 p-4">
                    <div className="text-[10px] uppercase tracking-[0.22em] text-slate-400">{item.label}</div>
                    <div className="mt-1 text-sm font-semibold text-slate-950">{item.value}</div>
                  </div>
                ))}
              </div>
            </div>

            <button onClick={handlePayment} disabled={processing || !orderId} className="btn-primary w-full py-4 text-base">
              {processing ? 'Opening secure checkout...' : `Pay ₹${payableAmount.toLocaleString()} now`}
            </button>
            <p className="text-center text-xs text-slate-500">Your payment is secure. We use Razorpay for protected transactions and immediate booking verification.</p>
          </div>

          <aside className="space-y-4 lg:sticky lg:top-24 lg:self-start">
            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Amount breakdown</h3>
                <p className="booking-panel-subtitle">A calm floating summary that updates with coupon status.</p>
              </div>
              <div className="booking-panel-body space-y-3">
                <div className="rounded-[1.35rem] bg-slate-950 p-4 text-white shadow-lg">
                  <div className="text-xs uppercase tracking-[0.24em] text-slate-300/70">Payable now</div>
                  <div className="mt-2 text-3xl font-semibold text-orange-300">₹{payableAmount.toLocaleString()}</div>
                  <div className="mt-1 text-sm text-slate-200/80">Coupon discount is applied when enabled.</div>
                </div>

                <div className="space-y-2 text-sm text-slate-600">
                  <div className="flex justify-between gap-3"><span>Base amount</span><span>₹{totalAmount.toLocaleString()}</span></div>
                  <div className="flex justify-between gap-3"><span>Coupon</span><span>-₹{discount.toLocaleString()}</span></div>
                  <div className="flex justify-between gap-3 border-t border-slate-200 pt-2 font-bold text-slate-950"><span>Final amount</span><span>₹{payableAmount.toLocaleString()}</span></div>
                </div>

                <div className="rounded-[1.35rem] border border-slate-200 bg-slate-50 p-4">
                  <div className="text-xs uppercase tracking-[0.24em] text-slate-400">Payment mode</div>
                  <div className="mt-1 text-base font-semibold text-slate-950">{paymentMethods.find((method) => method.key === paymentMethod)?.label}</div>
                </div>

                <button type="button" onClick={() => setCouponApplied(Boolean(couponCode.trim()))} className="btn-secondary w-full justify-center">
                  <FiGift className="mr-2" /> Apply coupon
                </button>
              </div>
            </div>

            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Smart support</h3>
              </div>
              <div className="booking-panel-body space-y-3">
                {supportCards.map((card) => (
                  <div key={card.title} className="rounded-[1.35rem] border border-slate-200 bg-slate-50 p-4">
                    <div className="text-sm font-semibold text-slate-950">{card.title}</div>
                    <div className="mt-1 text-sm text-slate-600">{card.value}</div>
                  </div>
                ))}
              </div>
            </div>

            <div className="booking-panel">
              <div className="booking-panel-header">
                <h3 className="booking-panel-title">Quick actions</h3>
              </div>
              <div className="booking-panel-body space-y-3">
                <Link to={`/booking/${bookingId}`} className="btn-secondary w-full justify-center">
                  Review booking <FiArrowRight className="ml-2" />
                </Link>
                <button type="button" onClick={() => navigate('/dashboard')} className="btn-secondary w-full justify-center">
                  Back to dashboard
                </button>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </PublicPageShell>
  );
}